# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user1 = User.create(name: "Max", password: "123")

character1 = Character.create(user: user1, name: "Clint", level: 1, character_class: "Paladin", skills: ["Acrobatics", "Deception", "Persuasion", "Charisma"], spellcasting_ability: ["CHA"], armorclass: 15, subclass: "Devotion", speed: "30", strength: 14, dexterity: 12, constitution: 14, intelligence: 8, wisdom: 10, charisma: 16, hp_current: 12, hp_max: 12, weapons: ["Javelin", "Dagger"], equipment: ["Shield", "Warhammer"], background: "Acolyte", race: "Halfling", subrace: "Lightfoot", gold: 100, ideals: "I believe there is good in everyone", personality: "Bubbly and kind to everyone", flaws: "Will believe anyone, even bad people", bonds: "My mother, she raised me alone. I never saw a woman so kind and so pure.", features: ["Divine Sense, Lay on Hands"], languages: ["Common", "Halfling", "Elvish"], traits: ["Lucky", "Brave", "Halfling-Nimbleness"], spells: [], cantrips: [], alignment: "Neutral", hit_die: 10)

proficiencies1 = ProficiencyList.create(character: character1, strength: false, dexterity: false, constitution: false, intelligence: false, wisdom: true, charisma: true, acrobatics: false, animal_handling: false, arcana: false, athletics: true, deception: false, history: true, insight: true, intimidation: false, investigation: false, medicine: false, nature: false, perception: false, performance: false, persuasion: false, religion: true, sleight_of_hand: false, stealth: false, survival: true)

acolyte = Background.create(name: "Acolyte", skills: ["Insight", "Religion"], desc: "You have spent your life in the service of a temple to a specific god. You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine.")
charlatan = Background.create(name: "Charlatan", skills: ["Deception", "Sleight of Hand"], desc: "You have always had a way with people. You know what makes them tick and with a few leading questions you can read them like they were children's books. It's a useful talent, and one that you're perfectly willing to use for your advantage.")
criminal = Background.create(name: "Criminal", skills: ["Deception", "Stealth"], desc: "You are an experienced criminal with a history of breaking the law. You have spent a lot of time among other criminals and still have contacts within the criminal underworld. You're far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization.")
entertainer = Background.create(name: "Entertainer", skills: ["Acrobatics", "Performance"], desc: "You thrive in front of an audience. You know how to entrance them, entertain them, and even inspire them. Your poetics and music can raise their spirits or capture their sorrow")
folk_hero = Background.create(name: "Folk Hero", skills: ["Animal Handling", "Survival"], desc: "You come from a humble social rank, but you are destined for so much more. Already the people of your home village regard you as their champion, and your destiny calls you to stand against the tyrants and monsters that threaten the common folk everywhere.")
guild_artisan = Background.create(name: "Guild Artisan", skills: ["Insight", "Persuasion"], desc: "You are a member of an artisan's guild, skilled in a particular field and closely associated with other artisans. You are a well-established part of the mercantile world, freed by talent and wealth from the constraints of a feudal social order.")
hermit = Background.create(name: "Hermit", skills: ["Medicine", "Religion"], desc: "You lived in seclusion, either in a sheltered community such as a monastery, or entirely alone. In your time apart from the clamor of society, you found quiet, solitude, and perhaps some of the answers you were looking for.")
noble = Background.create(name: "Noble", skills: ["History", "Persuasion"], desc: "You understand wealth, power, and privilege. You carry a noble title, and your family owns land, collects taxes, and wields significant political influence.")
outlander = Background.create(name: "Outlander", skills: ["Athletics", "Survival"], desc: "You grew up in the wilds, far from civiliation and the comforts of town and technology. You've witnessed the migration of herds larger than forests, survived weather more extreme than any city-dweller could comprehend, and enjoyed the solitude of being the only thinking creature for miles in any direction.")
sage = Background.create(name: "Sage", skills: ["Arcana", "History"], desc: "You spent years learning the lore of the multiverse. You scoured manuscripts, studied scrolls, and listened to the greatest experts on the subjects that interest you. Your efforts have made you a master in your fields of study.")
sailor = Background.create(name: "Sailor", skills: ["Athletics", "Perception"], desc: "You sailed on a seagoing vessel for years. In that time, you faced down mighty storms, monsters of the deep, and those who wanted to sink your craft to the bottomless depths. Your first love is the distant line of the horizon, but the time has come to try your hand at something new.")
soldier = Background.create(name: "Soldier", skills: ["Athletics", "Intimidation"], desc: "War has been your life for as long as you care to remember. You trained as a youth, studied the use of weapons and armor, learned basic survival techniques, including how to stay alive on the battlefield. You might have been part of a standing national army or a mercenary company, or perhaps a member of a local militia who rose to prominence during a recent war.")
urchin = Background.create(name: "Urchin", skills: ["Sleight of Hand", "Stealth"], desc: "You grew up on the streets alone, orphaned and poor. You had no one to watch over you or provide for you, so you learned to provide for yourself. You fought fiercely over food and kept a constant watch out for other desperate souls who might steal from you.")
